-- Intentionally empty: this migration failed because source_videos table did not exist yet.
-- The full table creation is handled in the follow-up migration 20260608100100_create_uniquify_tables.
-- On production run: npx prisma migrate resolve --rolled-back "20260608100000_fix_source_video_fps_decimal"
